apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: marfeelns
data:
  nginx.conf: |
    # Based on https://www.nginx.com/resources/wiki/start/topics/examples/full/#nginx-conf

    #user              www www;  ## Default: nobody


    worker_processes  auto;

    error_log         "/opt/bitnami/nginx/logs/error.log";

    pid               "/opt/bitnami/nginx/tmp/nginx.pid";


    events {
        worker_connections  1024;
    }


    http {
        #include        /opt/bitnami/nginx/conf/mime.types;
        default_type  application/octet-stream;
        log_format    main '$remote_addr - $remote_user [$time_local] '
                          '"$request" $status  $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';
        access_log    "/opt/bitnami/nginx/logs/access.log" main;
        #add_header    X-Frame-Options SAMEORIGIN;
        keepalive_timeout  120;

        sendfile           on;
        proxy_max_temp_file_size 0;
        
        
        include  "/opt/bitnami/nginx/conf/server_blocks/*.conf";

        # HTTP Server
        server {
          listen 0.0.0.0:8080;
          
          root /app;
          index welcomepage.html;

          #ssl_certificate /etc/letsencrypt/live/avocado.lol/fullchain.pem;
          #ssl_certificate_key /etc/letsencrypt/live/avocado.lol/privkey.pem;
          
        

        
        
        
      }         
